---
abstract: 'Run processes in parallel based on CPU usage'
author:
  - 'Jason McCarver <slam@parasite.cc>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-ForkManager-Scaled
no_index:
  directory:
    - .hg
    - examples
    - inc
    - t
requires:
  List::Util: 0
  Moo: 0
  Parallel::ForkManager: 0
  Unix::Statgrab: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/jmccarv/perl-parallel-forkmanager-scaled
version: '0.11'
